services:
  django:
    build: .
    container_name: cmsmc_${ENVIRON}
    env_file: "cmsmc/.env"
    volumes:
      - ./data:/data
      - ./staticfiles:/staticfiles
      - ./media:/media
    ports:
      - "127.0.0.1:${APP_PORT}:8088"
    restart: unless-stopped
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR}


networks:
  cluster-network:
    name: cluster-network
    external: true
